export const PERSIST = "SAVE";
export const DIRTY_CHECK = "CHANGE";
export const REVERT = "REVERT";

export const LANGUAGES_UPDATE = "LANGUAGES_UPDATE";

export const TRANSLATIONS_UPDATE = "TRANSLATIONS_UPDATE";

export const TRANSLATION_GROUP_ADD = "TRANSLATION_GROUP_ADD";
export const TRANSLATION_GROUP_REMOVE = "TRANSLATION_GROUP_REMOVE";
export const TRANSLATION_ADD = "TRANSLATION_ADD";
export const TRANSLATION_EDIT = "TRANSLATION_EDIT";
export const TRANSLATION_REMOVE = "TRANSLATION_REMOVE";
